Realice layout_delete
erikMaggio/free-shop pull request #13
Opened 2023-07-14 18:57 UTC by cristianpesse

Realice layout_delete, Agregue background_delete en drawable y agregue texto en strings. 
![image](https://github.com/erikMaggio/free-shop/assets/115426493/5c2d15ee-6a45-455a-8436-566994b262c2)

2023-07-15 23:48 UTC, KevinMaggio requested changes

2023-07-15 23:48 UTC, KevinMaggio commented on app/src/main/java/com/example/freeshop/ui/DeleteActivity.kt
En DeleteActivity no se dejo el renglon libre

2023-07-15 23:48 UTC, KevinMaggio commented on app/src/main/res/layout/activity_delete.xml
sustraer el Color 
![image](https://github.com/erikMaggio/free-shop/assets/86111731/b7b8ba5d-6d2f-46c3-9049-407cd514cd2b)

2023-07-15 23:48 UTC, KevinMaggio commented on app/src/main/res/values/strings.xml
Quedo un espacio en Blanco

2023-07-15 23:49 UTC, KevinMaggio commented on app/src/main/java/com/example/freeshop/ui/DeleteActivity.kt
Okas gracias!

2023-07-16 01:35 UTC, erikMaggio commented on app/src/main/AndroidManifest.xml
falta agregar el activity delete a la carpeta UI y cambiar manifest

2023-07-16 01:35 UTC, erikMaggio commented on app/src/main/res/layout/activity_delete.xml
agregar los colores de background 

utilizar tamaños predeterminados de los edit  , tv, bt

los margin tienen q tener medidas de patron , margin 12dp , utilizar guideline para adaptar las medidas al figma

corregir el nombre del string de delete/eliminar

2023-07-16 01:35 UTC, erikMaggio commented on app/src/main/res/values/strings.xml
corregir string  delete a su nombre apropiado 

utilizaremos como patron  el nombre de los botones = bt

2023-07-18 01:04 UTC, cristianpesse commented on app/src/main/java/com/example/freeshop/ui/DeleteActivity.kt
ok, gracias. ahi modifico!

2023-07-18 01:05 UTC, cristianpesse commented on app/src/main/res/layout/activity_delete.xml
ok gracias, ahi modifico.

2023-07-18 01:15 UTC, cristianpesse commented on app/src/main/res/values/strings.xml
Ok, ahi lo corrijo, gracias!

2023-07-18 01:15 UTC, cristianpesse commented on app/src/main/res/values/strings.xml
ok, gracias ahi modifico.

2023-07-18 01:16 UTC, cfp-dev8 commented on app/src/main/AndroidManifest.xml
ok, gracias ahi modifico.

2023-07-18 01:18 UTC, cristianpesse commented on app/src/main/res/layout/activity_delete.xml
ok, gracias ahi lo corrijo.

2023-07-18 01:25 UTC, cristianpesse commented on app/src/main/res/values/strings.xml
ok gracias ahi corrijo.

2023-07-18 17:35 UTC, merged